'use client'

import React, { useState, useTransition } from 'react'
import { motion, AnimatePresence } from 'framer-motion'
import { Badge } from '@/components/ui/badge'
import { Card, CardHeader, CardTitle, CardContent } from '@/components/ui/card'
import {
  ShieldAlert, FileSearch, Fingerprint, BrainCircuit,
  Flag, Archive, CheckCircle2, Download, Save,
  FileText, Link as LinkIcon, ExternalLink, Loader2,
  AlertTriangle, Sparkles
} from 'lucide-react'
import { updateCaseStatus, saveAnalystNotes } from './actions'

type Listing = {
  id: string
  title: string
  description: string
  seller: string
  url: string
  postedTime: string
  riskLevel: string
  confidenceScore: number
  explanation: string
  matchedWords: string
  status: string
  analystNotes: string
  platform: { name: string }
}

type SimilarCase = {
  id: string
  title: string
  riskLevel: string
  confidenceScore: number
  seller: string
  platform: { name: string }
  postedTime: string
}

const STATUS_CONFIG = {
  ACTIVE: { label: 'Active', color: 'text-primary border-primary/40 bg-primary/10', icon: AlertTriangle },
  FLAGGED: { label: 'Flagged for Enforcement', color: 'text-amber-400 border-amber-400/40 bg-amber-400/10', icon: Flag },
  ARCHIVED: { label: 'Archived', color: 'text-muted-foreground border-border bg-muted/10', icon: Archive },
  RESOLVED: { label: 'Case Resolved', color: 'text-emerald-400 border-emerald-400/40 bg-emerald-400/10', icon: CheckCircle2 },
} as const

export function CaseFileClient({ listing, similar, matchedWords }: {
  listing: Listing
  similar: SimilarCase[]
  matchedWords: string[]
}) {
  const [status, setStatus] = useState(listing.status as keyof typeof STATUS_CONFIG)
  const [notes, setNotes] = useState(listing.analystNotes)
  const [notesSaved, setNotesSaved] = useState(false)
  const [isPending, startTransition] = useTransition()

  const handleStatusChange = (newStatus: keyof typeof STATUS_CONFIG) => {
    setStatus(newStatus)
    startTransition(() => updateCaseStatus(listing.id, newStatus))
  }

  const handleSaveNotes = () => {
    startTransition(async () => {
      await saveAnalystNotes(listing.id, notes)
      setNotesSaved(true)
      setTimeout(() => setNotesSaved(false), 3000)
    })
  }

  const handlePDFExport = () => {
    const content = `
AEGIS INTEL — CASE FILE REPORT
================================
Case ID:     ${listing.id.split('-')[0].toUpperCase()}
Intercepted: ${new Date(listing.postedTime).toLocaleString()}
Status:      ${status}

LISTING TITLE
-------------
${listing.title}

PLATFORM: ${listing.platform.name}   |   SELLER: ${listing.seller}
SOURCE URL: ${listing.url}

AI CONFIDENCE ENGINE: ${listing.confidenceScore}%
RISK LEVEL: ${listing.riskLevel}

DETECTION REASONING
-------------------
${listing.explanation}

IDENTIFIED TRIGGERS: ${matchedWords.join(', ') || 'None'}

RAW EVIDENCE TEXT
-----------------
${listing.description}

ANALYST NOTES
-------------
${notes || '[No analyst notes recorded]'}

Generated by Aegis Intelligence Platform
    `.trim()

    const blob = new Blob([content], { type: 'text/plain' })
    const a = document.createElement('a')
    a.href = URL.createObjectURL(blob)
    a.download = `case-file-${listing.id.split('-')[0]}.txt`
    a.click()
    URL.revokeObjectURL(a.href)
  }

  const CurrentStatusIcon = STATUS_CONFIG[status]?.icon ?? AlertTriangle

  return (
    <div className="space-y-6">
      {/* Action Bar */}
      <motion.div
        initial={{ opacity: 0, y: -10 }}
        animate={{ opacity: 1, y: 0 }}
        className="flex flex-wrap items-center gap-3 p-4 rounded-xl border border-border/50 bg-card/50 backdrop-blur-sm"
      >
        <span className="text-xs font-mono uppercase tracking-widest text-muted-foreground mr-2">Case Status:</span>

        {/* Status Badge */}
        <div className={`flex items-center gap-2 px-3 py-1.5 rounded-full border text-xs font-bold font-mono uppercase tracking-widest ${STATUS_CONFIG[status]?.color}`}>
          <CurrentStatusIcon className="w-3.5 h-3.5" />
          {STATUS_CONFIG[status]?.label}
          {isPending && <Loader2 className="w-3 h-3 animate-spin ml-1" />}
        </div>

        <div className="ml-auto flex flex-wrap gap-2">
          <button
            onClick={() => handleStatusChange('FLAGGED')}
            disabled={status === 'FLAGGED' || isPending}
            className="flex items-center gap-2 px-4 py-2 rounded-md border border-amber-500/40 bg-amber-500/10 text-amber-400 hover:bg-amber-500/20 text-xs font-bold uppercase tracking-widest transition-all disabled:opacity-40"
          >
            <Flag className="w-3.5 h-3.5" /> Flag for Enforcement
          </button>
          <button
            onClick={() => handleStatusChange('ARCHIVED')}
            disabled={status === 'ARCHIVED' || isPending}
            className="flex items-center gap-2 px-4 py-2 rounded-md border border-border bg-background/50 text-muted-foreground hover:text-foreground hover:bg-sidebar text-xs font-bold uppercase tracking-widest transition-all disabled:opacity-40"
          >
            <Archive className="w-3.5 h-3.5" /> Archive
          </button>
          <button
            onClick={() => handleStatusChange('RESOLVED')}
            disabled={status === 'RESOLVED' || isPending}
            className="flex items-center gap-2 px-4 py-2 rounded-md border border-emerald-500/40 bg-emerald-500/10 text-emerald-400 hover:bg-emerald-500/20 text-xs font-bold uppercase tracking-widest transition-all disabled:opacity-40"
          >
            <CheckCircle2 className="w-3.5 h-3.5" /> Mark Resolved
          </button>
          <button
            onClick={handlePDFExport}
            className="flex items-center gap-2 px-4 py-2 rounded-md bg-primary/10 border border-primary/40 text-primary hover:bg-primary/20 text-xs font-bold uppercase tracking-widest transition-all shadow-[0_0_10px_-3px_var(--color-primary)]"
          >
            <Download className="w-3.5 h-3.5" /> Export Case
          </button>
        </div>
      </motion.div>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        {/* Main Analysis Column */}
        <div className="col-span-1 lg:col-span-2 space-y-6">

          {/* AI Reasoning */}
          <Card className="border-border/50 bg-card/60 backdrop-blur-sm relative overflow-hidden">
            <CardHeader className="border-b border-border/50 pb-4">
              <CardTitle className="flex items-center gap-2 text-lg uppercase tracking-wide">
                <BrainCircuit className="w-5 h-5 text-primary" />
                Detection Logic & AI Reasoning
              </CardTitle>
            </CardHeader>
            <CardContent className="pt-6">
              <div className="p-4 rounded-md bg-destructive/10 border border-destructive/20 text-destructive-foreground font-mono text-sm leading-relaxed">
                &gt; ENG_DIAGNOSTIC: {listing.explanation}
              </div>
              <div className="mt-6">
                <h4 className="text-xs font-mono uppercase tracking-widest text-muted-foreground mb-3">Identified Syntax Triggers</h4>
                <div className="flex flex-wrap gap-2">
                  {matchedWords.map((word, i) => (
                    <Badge key={i} variant="outline" className="border-primary bg-primary/10 text-primary font-mono lowercase px-3 py-1 shadow-[0_0_10px_-2px_var(--color-primary)]">
                      {word}
                    </Badge>
                  ))}
                  {matchedWords.length === 0 && <span className="text-xs text-muted-foreground font-mono opacity-50">NULL</span>}
                </div>
              </div>
            </CardContent>
          </Card>

          {/* Evidence Capture */}
          <Card className="border-border/50 bg-card/60 backdrop-blur-sm">
            <CardHeader className="border-b border-border/50 pb-4">
              <CardTitle className="flex items-center gap-2 text-lg uppercase tracking-wide">
                <FileSearch className="w-5 h-5 text-primary" />
                Evidence Capture: Raw Feed
              </CardTitle>
            </CardHeader>
            <CardContent className="pt-6 font-mono text-sm text-foreground/80 leading-relaxed">
              <p className="whitespace-pre-wrap pl-4 border-l-2 border-primary/50">
                {listing.description.split(new RegExp(`(${matchedWords.join('|')})`, 'gi')).map((part, i) =>
                  matchedWords.some(w => w.toLowerCase() === part.toLowerCase()) ? (
                    <mark key={i} className="bg-destructive/20 text-destructive-foreground px-1 rounded-sm border border-destructive/30 outline outline-1 outline-offset-1 outline-destructive/20 filter drop-shadow-[0_0_5px_rgba(225,29,72,0.8)] font-bold">{part}</mark>
                  ) : (
                    <span key={i}>{part}</span>
                  )
                )}
              </p>
            </CardContent>
          </Card>

          {/* Analyst Notes */}
          <Card className="border-border/50 bg-card/60 backdrop-blur-sm">
            <CardHeader className="border-b border-border/50 pb-4">
              <CardTitle className="flex items-center gap-2 text-lg uppercase tracking-wide">
                <FileText className="w-5 h-5 text-primary" />
                Analyst Notes
              </CardTitle>
            </CardHeader>
            <CardContent className="pt-6 space-y-4">
              <textarea
                value={notes}
                onChange={(e) => setNotes(e.target.value)}
                rows={5}
                placeholder="Add investigation notes, linked cases, or enforcement recommendations..."
                className="w-full bg-background/50 border border-border/60 rounded-lg p-4 text-sm font-mono text-foreground/80 placeholder:text-muted-foreground/40 outline-none focus:border-primary/60 focus:ring-1 focus:ring-primary/30 transition-all resize-none"
              />
              <div className="flex items-center justify-between">
                <AnimatePresence>
                  {notesSaved && (
                    <motion.span
                      initial={{ opacity: 0, y: 4 }}
                      animate={{ opacity: 1, y: 0 }}
                      exit={{ opacity: 0 }}
                      className="text-xs font-mono text-emerald-400 flex items-center gap-1"
                    >
                      <CheckCircle2 className="w-3.5 h-3.5" /> Notes saved to case record.
                    </motion.span>
                  )}
                  {!notesSaved && <span />}
                </AnimatePresence>
                <button
                  onClick={handleSaveNotes}
                  disabled={isPending}
                  className="flex items-center gap-2 px-5 py-2 rounded-md bg-primary text-primary-foreground text-xs font-bold uppercase tracking-widest hover:bg-primary/90 transition-all shadow-[0_0_12px_-3px_var(--color-primary)] disabled:opacity-50"
                >
                  {isPending ? <Loader2 className="w-3.5 h-3.5 animate-spin" /> : <Save className="w-3.5 h-3.5" />}
                  Save Notes
                </button>
              </div>
            </CardContent>
          </Card>
        </div>

        {/* Right Sidebar */}
        <div className="col-span-1 space-y-6">
          {/* Target Metadata */}
          <Card className="border-border/50 bg-card/40 backdrop-blur-sm">
            <CardHeader className="border-b border-border/50 pb-4">
              <CardTitle className="flex items-center gap-2 text-sm uppercase tracking-wider">
                <Fingerprint className="w-4 h-4 text-primary" />
                Target Metadata
              </CardTitle>
            </CardHeader>
            <CardContent className="pt-6 space-y-4 font-mono text-sm">
              <div>
                <span className="block text-xs text-muted-foreground mb-1 uppercase tracking-widest">Network Origin</span>
                <span className="font-semibold">{listing.platform.name}</span>
              </div>
              <div className="h-px w-full bg-border/50" />
              <div>
                <span className="block text-xs text-muted-foreground mb-1 uppercase tracking-widest">Seller Alias</span>
                <span className="font-semibold text-primary">{listing.seller}</span>
              </div>
              <div className="h-px w-full bg-border/50" />
              <div>
                <span className="block text-xs text-muted-foreground mb-1 uppercase tracking-widest">Original Transmission</span>
                <a
                  href={listing.url}
                  target="_blank"
                  rel="noopener noreferrer"
                  className="flex items-center gap-2 text-muted-foreground hover:text-primary transition-colors hover:underline"
                >
                  <span className="truncate max-w-[180px]">{listing.url}</span>
                  <ExternalLink className="w-3 h-3 flex-shrink-0" />
                </a>
              </div>
            </CardContent>
          </Card>

          {/* Similar Cases */}
          {similar.length > 0 && (
            <Card className="border-border/50 bg-card/40 backdrop-blur-sm">
              <CardHeader className="border-b border-border/50 pb-4">
                <CardTitle className="flex items-center gap-2 text-sm uppercase tracking-wider">
                  <Sparkles className="w-4 h-4 text-primary" />
                  AI-Similar Cases
                </CardTitle>
              </CardHeader>
              <CardContent className="pt-4 space-y-3">
                {similar.map((s) => (
                  <a
                    key={s.id}
                    href={`/alerts/${s.id}`}
                    className="block p-3 rounded-lg border border-border/40 bg-background/40 hover:border-primary/40 hover:bg-primary/5 transition-all group"
                  >
                    <div className="flex items-start justify-between gap-2 mb-1">
                      <span className="text-xs font-semibold text-foreground/80 group-hover:text-primary transition-colors line-clamp-2 leading-tight">{s.title}</span>
                      <span className={`text-[10px] font-black font-mono flex-shrink-0 ${s.riskLevel === 'HIGH_RISK' ? 'text-destructive' : 'text-amber-400'}`}>
                        {s.confidenceScore}%
                      </span>
                    </div>
                    <div className="flex items-center gap-2 text-[10px] font-mono text-muted-foreground">
                      <LinkIcon className="w-3 h-3" />
                      {s.platform.name}
                      <span className="text-muted-foreground/50">·</span>
                      {s.seller}
                    </div>
                  </a>
                ))}
              </CardContent>
            </Card>
          )}
        </div>
      </div>
    </div>
  )
}
